name: Crear IAM Roles

on:
  workflow_dispatch:

jobs:
  setup-iam:
    runs-on: ubuntu-latest
    outputs:
      iam_instance_profile: ${{ steps.get-instance-profile.outputs.iam_instance_profile }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          terraform_wrapper: true

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply (IAM Roles)
        id: terraform-apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
          -target=module.iam.aws_iam_role.ec2_cloudwatch_role \
          -target=module.iam.aws_iam_role_policy.ec2_cloudwatch_policy \
          -target=module.iam.aws_iam_instance_profile.ec2_cloudwatch_profile

      - name: Get IAM Instance Profile
        id: get-instance-profile
        run: |
          IAM_INSTANCE_PROFILE=$(terraform -chdir=terraform output -raw iam_instance_profile)
          echo "iam_instance_profile=$IAM_INSTANCE_PROFILE" >> $GITHUB_OUTPUT

      - name: Trigger VPC Workflow
        uses: pauldraper/workflow-dispatch@v1.6
        with:
          workflow: vpc.yml
          inputs: |
            {
              "iam_instance_profile": "${{ steps.get-instance-profile.outputs.iam_instance_profile }}"
            }
